### ISSUE TITLE
Problem with run

### ISSUE THREAD

**Issue by bayramdogangocer** [komamitsu/Android-OCRSample#1]
I imported the Eclipse this project.After that show the tess-two library from tesseract.But Ide underlines the AVS_MOST_ACCURATE and PSM_SINGLE_LINE

 baseAPI.setPageSegMode(TessBaseAPI.AVS_MOST_ACCURATE);
  baseAPI.setPageSegMode(TessBaseAPI.PSM_SINGLE_LINE);

How can I solve this problem?

**Comment by pradyut** [comment]
Change those two lines to this:

baseAPI.setPageSegMode(TessBaseAPI.AVS_MOST_ACCURATE);
baseAPI.setPageSegMode(TessBaseAPI.PageSegMode.PSM_SINGLE_LINE);

**Comment by Jaymin-Bhadani** [comment]
can not find baseAPI.setPageSegMode(TessBaseAPI.AVS_MOST_ACCURATE);

**Comment by komamitsu** [comment]
Thanks for trying and/or using this example Android application and sorry for my really late reply. I missed notifications on this issue for a long time...

I noticed it's really hard to use Tesseract with current Android SDK/NDK. So I updated this example application to use Google Text Recognition API.
